version: "3.8"

services:
  db:
    image: postgres:13.12-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$FRONTEND_PORT"
      BASE_URL: "http://localhost:$BACKEND_PORT"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./backend:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$BACKEND_PORT:3000"

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$BACKEND_PORT"
    command: yarn run dev
    volumes:
      - "./frontend:/$WORKDIR"
    ports:
      - "$FRONTEND_PORT:3000"
    depends_on:
      - backend
